Repository pyronear/pyro-crowdsourcer, pull requests merged in 2022-06, with the labels that each got.

#19 Move to dash
  .github/workflows/docker.yml
  .github/workflows/main.yml
  Dockerfile
  Procfile
  requirements.txt
  src/app.py
Labels: enhancement

#20 Design edits
  requirements.txt
  src/app.py
Labels: enhancement

#21 ci: Updated funding from OpenCollective to Github
  .github/FUNDING.yml
Labels: enhancement, topic: build

#22 style: Added black formatting and mypy
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/collect_env.py
  .github/workflows/scripts.yml
  .github/workflows/style.yml
  .isort.cfg
  pyproject.toml
  src/app.py
  src/config.py
Labels: enhancement, topic: build

#26 docs: Updated README and version specifier for pyrostorage
  CONTRIBUTING.md
  Dockerfile
  README.md
  requirements.txt
Labels: documentation

#27 ci: Removed release note generation file
  .github/release.yml
Labels: topic: build

#28 ci: Added header checking job
  .github/validate_headers.py
  .github/workflows/main.yml
  src/services/api.py
Labels: enhancement, topic: build
